server:
  port: 9080

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: pass
    realmImportFile: realm-export.json
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://admin:admin@localhost:8761/eureka/
